development:
  adapter: postgresql
  database: skuleorientation
  host: localhost
  username: william
  password: 123456
test:
  adapter: postgresql
  database: skuleorientation-test
  host: localhost
  min_messages: WARNING
  username: william
  password: 123456
